In [1]:
import boto
import csv
import numpy as np
import pandas as pd
import scipy.stats as stats

c = boto.connect_s3()
b = c.get_bucket('nichung-datasets')

In [3]:
mergeNY13_df = pd.read_csv('s3:/nichung-datasets/ss13ny.csv')

In [5]:
mergeNY14_df = pd.read_csv('s3:/nichung-datasets/ss14ny.csv')

In [4]:
mergeNY15_df = pd.read_csv('s3:/nichung-datasets/ss15ny.csv')

In [4]:
ny_puma_df = pd.read_csv('s3:/nichung-datasets/puma_ny.csv')

In [14]:
mergeNY13_df.head()

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1,RT_x,SERIALNO,SPORDER,PUMA,ST_x,ADJINC_x,...,wgtp72,wgtp73,wgtp74,wgtp75,wgtp76,wgtp77,wgtp78,wgtp79,wgtp80,age_group_13
0,0,0,0,0,P,10,1.0,1201.0,36.0,1007549.0,...,166,166,44,127,267,260,259,161,49,>65
1,1,1,1,1,P,27,1.0,1000.0,36.0,1007549.0,...,38,59,43,35,31,7,28,35,10,>65
2,2,2,2,2,P,27,2.0,1000.0,36.0,1007549.0,...,38,59,43,35,31,7,28,35,10,55-64
3,3,3,3,3,P,27,3.0,1000.0,36.0,1007549.0,...,38,59,43,35,31,7,28,35,10,18-24
4,4,4,4,4,P,36,1.0,4011.0,36.0,1007549.0,...,97,181,96,27,95,27,26,154,95,>65

In [15]:
mergeNY13_df.drop(mergeNY13_df.columns[[0, 1, 2]], axis=1)

,RT_x,SERIALNO,SPORDER,PUMA,ST_x,ADJINC_x,PWGTP,AGEP,CIT,CITWP,...,wgtp72,wgtp73,wgtp74,wgtp75,wgtp76,wgtp77,wgtp78,wgtp79,wgtp80,age_group_13
0,P,10,1.0,1201.0,36.0,1007549.0,154.0,78.0,1.0,NaN,...,166,166,44,127,267,260,259,161,49,>65
1,P,27,1.0,1000.0,36.0,1007549.0,30.0,68.0,4.0,1980.0,...,38,59,43,35,31,7,28,35,10,>65
2,P,27,2.0,1000.0,36.0,1007549.0,32.0,58.0,4.0,2013.0,...,38,59,43,35,31,7,28,35,10,55-64
3,P,27,3.0,1000.0,36.0,1007549.0,43.0,24.0,5.0,NaN,...,38,59,43,35,31,7,28,35,10,18-24
4,P,36,1.0,4011.0,36.0,1007549.0,95.0,78.0,1.0,NaN,...,97,181,96,27,95,27,26,154,95,>65
5,P,58,1.0,1500.0,36.0,1007549.0,23.0,52.0,1.0,NaN,...,6,10,35,32,7,23,38,7,27,45-54
6,P,58,2.0,1500.0,36.0,1007549.0,37.0,54.0,1.0,NaN,...,6,10,35,32,7,23,38,7,27,45-54
7,P,58,3.0,1500.0,36.0,1007549.0,32.0,16.0,1.0,NaN,...,6,10,35,32,7,23,38,7,27,<18
8,P,58,4.0,1500.0,36.0,1007549.0,44.0,9.0,1.0,NaN,...,6,10,35,32,7,23,38,7,27,<18
9,P,58,5.0,1500.0,36.0,1007549.0,44.0,12.0,1.0,NaN,...,6,10,35,32,7,23,38,7,27,<18
10,P,61,1.0,3808.0,36.0,1007549.0,89.0,19.0,1.0,NaN,...,0,0,0,0,0,0,0,0,0,<18
11,P,72,1.0,2801.0,36.0,1007549.0,151.0,61.0,1.0,NaN,...,143,162,150,156,155,241,297,224,279,55-64
12,P,72,2.0,2801.0,36.0,1007549.0,168.0,60.0,1.0,NaN,...,143,162,150,156,155,241,297,224,279,55-64
13,P,72,3.0,2801.0,36.0,1007549.0,155.0,26.0,1.0,NaN,...,143,162,150,156,155,241,297,224,279,25-34
14,P,92,1.0,4003.0,36.0,1007549.0,115.0,50.0,2.0,NaN,...,97,102,98,115,224,37,140,104,190,45-54
15,P,92,2.0,4003.0,36.0,1007549.0,110.0,28.0,1.0,NaN,...,97,102,98,115,224,37,140,104,190,25-34
16,P,92,3.0,4003.0,36.0,1007549.0,137.0,21.0,1.0,NaN,...,97,102,98,115,224,37,140,104,190,18-24
17,P,92,4.0,4003.0,36.0,1007549.0,93.0,2.0,1.0,NaN,...,97,102,98,115,224,37,140,104,190,<18
18,P,99,1.0,4111.0,36.0,1007549.0,47.0,69.0,2.0,NaN,...,67,74,15,13,82,54,14,78,52,>65
19,P,112,1.0,3105.0,36.0,1007549.0,346.0,59.0,1.0,NaN,...,333,397,585,335,344,355,343,594,377,55-64
20,P,112,2.0,3105.0,36.0,1007549.0,374.0,52.0,1.0,NaN,...,333,397,585,335,344,355,343,594,377,45-54
21,P,112,3.0,3105.0,36.0,1007549.0,311.0,11.0,1.0,NaN,...,333,397,585,335,344,355,343,594,377,<18
22,P,112,4.0,3105.0,36.0,1007549.0,309.0,7.0,1.0,NaN,...,333,397,585,335,344,355,343,594,377,<18
23,P,119,1.0,3105.0,36.0,1007549.0,353.0,30.0,4.0,2008.0,...,617,482,383,325,336,373,320,99,630,25-34
24,P,119,2.0,3105.0,36.0,1007549.0,215.0,34.0,4.0,2010.0,...,617,482,383,325,336,373,320,99,630,25-34
25,P,133,1.0,704.0,36.0,1007549.0,26.0,58.0,1.0,NaN,...,10,40,27,29,47,28,47,26,10,55-64
26,P,133,2.0,704.0,36.0,1007549.0,26.0,61.0,1.0,NaN,...,10,40,27,29,47,28,47,26,10,55-64
27,P,133,3.0,704.0,36.0,1007549.0,52.0,21.0,1.0,NaN,...,10,40,27,29,47,28,47,26,10,18-24
28,P,143,1.0,3201.0,36.0,1007549.0,81.0,59.0,1.0,NaN,...,90,24,82,152,89,86,125,97,22,55-64
29,P,143,2.0,3201.0,36.0,1007549.0,77.0,60.0,1.0,NaN,...,90,24,82,152,89,86,125,97,22,55-64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203213,NaN,1486318,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,243,265,142,48,161,261,165,134,45,NaN
203214,NaN,1486536,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,45,46,54,53,51,98,52,16,13,NaN
203215,NaN,1486770,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,44,39,246,225,132,146,144,148,226,NaN
203216,NaN,1486798,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,63,34,11,59,29,66,33,10,52,NaN
203217,NaN,1486875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,76,20,78,22,75,73,70,125,116,NaN
203218,NaN,1486919,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,202,217,63,302,208,192,56,189,229,NaN
203219,NaN,1486967,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,96,18,61,60,54,18,64,61,18,NaN
203220,NaN,1487130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,59,39,39,59,33,34,62,39,42,NaN
203221,NaN,1487163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,144,225,141,227,232,42,43,146,139,NaN
203222,NaN,1487478,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,516,589,335,114,385,569,355,373,100,NaN
203223,NaN,1487531,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,58,30,27,27,7,31,45,23,29,NaN
203224,NaN,1487782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,296,47,158,299,49,44,166,175,155,NaN
203225,NaN,1488015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,104,193,136,212,97,103,130,31,235,NaN
203226,NaN,1488179,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17,17,18,5,4,19,18,16,16,NaN
203227,NaN,1488579,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,126,26,25,142,85,25,169,147,93,NaN
203228,NaN,1489445,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,51,82,15,14,53,47,47,88,13,NaN
203229,NaN,1489522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,229,43,151,142,147,42,122,152,46,NaN
203230,NaN,1489607,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,151,28,130,105,97,26,96,173,155,NaN
203231,NaN,1489829,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,195,121,117,31,195,112,114,212,33,NaN
203232,NaN,1490058,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,61,100,57,18,18,15,54,57,101,NaN
203233,NaN,1490226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,210,203,39,122,135,216,37,145,40,NaN
203234,NaN,1490304,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,440,339,354,66,209,193,369,63,354,NaN
203235,NaN,1490369,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,165,178,285,46,160,179,277,174,176,NaN
203236,NaN,1490396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,210,206,65,64,59,215,392,222,63,NaN
203237,NaN,1490419,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,116,103,101,177,106,188,110,107,178,NaN
203238,NaN,1491904,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,167,288,147,50,46,149,157,47,175,NaN
203239,NaN,1492157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,120,20,75,22,70,74,22,74,73,NaN
203240,NaN,1492178,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,75,81,119,76,24,79,23,22,84,NaN
203241,NaN,1492411,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,56,36,38,33,34,34,10,12,11,NaN
203242,NaN,1492844,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,57,113,79,57,59,97,17,21,59,NaN

In [16]:
puma_NY__13 = mergeNY13_df.PUMA
puma_NY__13.value_counts()

2500.0    3032
200.0     2571
4112.0    2421
403.0     2391
4009.0    2307
500.0     2297
2402.0    2212
4103.0    2194
2600.0    2105
4105.0    2027
2002.0    2007
704.0     1968
2203.0    1933
4017.0    1919
703.0     1878
1500.0    1878
1400.0    1873
4110.0    1857
1300.0    1844
4101.0    1813
100.0     1798
4111.0    1777
1207.0    1774
701.0     1761
3107.0    1757
2802.0    1745
401.0     1735
1900.0    1734
800.0     1722
402.0     1720
          ...
3809.0    1007
3001.0    1005
3002.0    1003
3209.0     999
1203.0     999
4107.0     996
3212.0     994
3210.0     983
3101.0     977
3312.0     974
1801.0     960
3807.0     954
903.0      953
4018.0     947
3313.0     947
2001.0     945
3708.0     937
1201.0     931
3211.0     907
3701.0     886
3803.0     876
4011.0     864
3307.0     848
3806.0     844
3802.0     808
4114.0     805
3706.0     794
3804.0     736
3703.0     712
3808.0     710
Name: PUMA, dtype: int64

In [17]:
access_puma_ny__13 = mergeNY13_df[['PUMA', 'ACCESS']]
access_puma_ny__13

          PUMA  ACCESS
0       1201.0     3.0
1       1000.0     1.0
2       1000.0     1.0
3       1000.0     1.0
4       4011.0     1.0
5       1500.0     1.0
6       1500.0     1.0
7       1500.0     1.0
8       1500.0     1.0
9       1500.0     1.0
10      3808.0     NaN
11      2801.0     1.0
12      2801.0     1.0
13      2801.0     1.0
14      4003.0     1.0
15      4003.0     1.0
16      4003.0     1.0
17      4003.0     1.0
18      4111.0     3.0
19      3105.0     1.0
20      3105.0     1.0
21      3105.0     1.0
22      3105.0     1.0
23      3105.0     1.0
24      3105.0     1.0
25       704.0     1.0
26       704.0     1.0
27       704.0     1.0
28      3201.0     1.0
29      3201.0     1.0
...        ...     ...
203213     NaN     NaN
203214     NaN     NaN
203215     NaN     NaN
203216     NaN     NaN
203217     NaN     NaN
203218     NaN     NaN
203219     NaN     NaN
203220     NaN     NaN
203221     NaN     NaN
203222     NaN     NaN
203223     NaN     NaN
203224     NaN     NaN
203225     NaN     NaN
203226     NaN     NaN
203227     NaN     NaN
203228     NaN     NaN
203229     NaN     NaN
203230     NaN     NaN
203231     NaN     NaN
203232     NaN     NaN
203233     NaN     NaN
203234     NaN     NaN
203235     NaN     NaN
203236     NaN     NaN
203237     NaN     NaN
203238     NaN     NaN
203239     NaN     NaN
203240     NaN     NaN
203241     NaN     NaN
203242     NaN     NaN

[203243 rows x 2 columns]

In [18]:
access_puma_ny__13.dropna(how='all')

          PUMA  ACCESS
0       1201.0     3.0
1       1000.0     1.0
2       1000.0     1.0
3       1000.0     1.0
4       4011.0     1.0
5       1500.0     1.0
6       1500.0     1.0
7       1500.0     1.0
8       1500.0     1.0
9       1500.0     1.0
10      3808.0     NaN
11      2801.0     1.0
12      2801.0     1.0
13      2801.0     1.0
14      4003.0     1.0
15      4003.0     1.0
16      4003.0     1.0
17      4003.0     1.0
18      4111.0     3.0
19      3105.0     1.0
20      3105.0     1.0
21      3105.0     1.0
22      3105.0     1.0
23      3105.0     1.0
24      3105.0     1.0
25       704.0     1.0
26       704.0     1.0
27       704.0     1.0
28      3201.0     1.0
29      3201.0     1.0
...        ...     ...
196135  3301.0     2.0
196136  3301.0     2.0
196137  3301.0     2.0
196138  3301.0     2.0
196139  3301.0     2.0
196140  3301.0     2.0
196141  1206.0     1.0
196142  4112.0     3.0
196143  4112.0     3.0
196144  3705.0     2.0
196145  3705.0     2.0
196146  3705.0     2.0
196147  3705.0     2.0
196148  3705.0     2.0
196149  3705.0     2.0
196150  1000.0     1.0
196151  1000.0     1.0
196152  3901.0     3.0
196153  3710.0     3.0
196154  3710.0     3.0
196155   600.0     1.0
196156   906.0     1.0
196157   906.0     1.0
196158  1204.0     1.0
196159  1204.0     1.0
196160   100.0     1.0
196161   100.0     1.0
196162  2500.0     NaN
196163  4013.0     3.0
196164  4013.0     3.0

[196165 rows x 2 columns]

In [19]:
# frequency table of PUMA vs. internet access
b_two_way__access_puma__13 = pd.crosstab(index=access_puma_ny__13["PUMA"], 
                                        columns=access_puma_ny__13["ACCESS"],
                                        margins=True)

b_two_way__access_puma__13

ACCESS     1.0   2.0    3.0     All
PUMA
100.0     1111    38    439    1588
200.0     1772    78    419    2269
300.0     1295    64    260    1619
401.0     1308    59    326    1693
402.0     1175    75    258    1508
403.0     1768    76    405    2249
500.0     1756   107    309    2172
600.0     1224    67    248    1539
701.0     1069    60    359    1488
702.0     1088    31     91    1210
703.0     1528    53    214    1795
704.0     1535    64    301    1900
800.0     1231    83    326    1640
901.0     1043    40    149    1232
902.0      743    50    340    1133
903.0      494    58    260     812
904.0      911    17    119    1047
905.0      903    14     78     995
906.0     1310    40     93    1443
1000.0    1122    50    250    1422
1101.0     779    40    219    1038
1102.0     863    28    170    1061
1201.0     791    19    105     915
1202.0     931     9    107    1047
1203.0     822    24     94     940
1204.0    1268    43    266    1577
1205.0     815    64    350    1229
1206.0     724    85    144     953
1207.0    1422    59    187    1668
1300.0    1303    91    269    1663
...        ...   ...    ...     ...
4004.0    1050    34    144    1228
4005.0     980    36     55    1071
4006.0     698    49    259    1006
4007.0     704    30    262     996
4008.0    1022    56    277    1355
4009.0    1951    83    241    2275
4010.0    1034    57    201    1292
4011.0     653    31    145     829
4012.0    1086    61    152    1299
4013.0    1176    50    164    1390
4014.0     896    78    691    1665
4015.0    1117    87    254    1458
4016.0    1367    45    244    1656
4017.0    1518    40    340    1898
4018.0     664    23    221     908
4101.0    1506    57    225    1788
4102.0     995    67    274    1336
4103.0    1720    47    367    2134
4104.0    1138    17    111    1266
4105.0    1689    42    242    1973
4106.0    1031    51    151    1233
4107.0     788    28    163     979
4108.0     873    10    116     999
4109.0     962    37    111    1110
4110.0    1470    54    310    1834
4111.0    1475    59    229    1763
4112.0    1876    89    390    2355
4113.0    1083    18    182    1283
4114.0     576    23    128     727
All     151743  6513  27085  185341

[146 rows x 4 columns]

In [20]:
b_two_way__access_puma__13 = b_two_way__access_puma__13.drop(['All'])

In [21]:
b_two_way__access_puma__13.to_csv('access_puma__13.csv')

In [22]:
puma_by_access__13 = pd.read_csv('access_puma__13.csv')

In [23]:
puma_by_access__13 = puma_by_access__13.astype(int)
puma_by_access__13

     PUMA   1.0  2.0  3.0   All
0     100  1111   38  439  1588
1     200  1772   78  419  2269
2     300  1295   64  260  1619
3     401  1308   59  326  1693
4     402  1175   75  258  1508
5     403  1768   76  405  2249
6     500  1756  107  309  2172
7     600  1224   67  248  1539
8     701  1069   60  359  1488
9     702  1088   31   91  1210
10    703  1528   53  214  1795
11    704  1535   64  301  1900
12    800  1231   83  326  1640
13    901  1043   40  149  1232
14    902   743   50  340  1133
15    903   494   58  260   812
16    904   911   17  119  1047
17    905   903   14   78   995
18    906  1310   40   93  1443
19   1000  1122   50  250  1422
20   1101   779   40  219  1038
21   1102   863   28  170  1061
22   1201   791   19  105   915
23   1202   931    9  107  1047
24   1203   822   24   94   940
25   1204  1268   43  266  1577
26   1205   815   64  350  1229
27   1206   724   85  144   953
28   1207  1422   59  187  1668
29   1300  1303   91  269  1663
..    ...   ...  ...  ...   ...
115  4003   715   57  380  1152
116  4004  1050   34  144  1228
117  4005   980   36   55  1071
118  4006   698   49  259  1006
119  4007   704   30  262   996
120  4008  1022   56  277  1355
121  4009  1951   83  241  2275
122  4010  1034   57  201  1292
123  4011   653   31  145   829
124  4012  1086   61  152  1299
125  4013  1176   50  164  1390
126  4014   896   78  691  1665
127  4015  1117   87  254  1458
128  4016  1367   45  244  1656
129  4017  1518   40  340  1898
130  4018   664   23  221   908
131  4101  1506   57  225  1788
132  4102   995   67  274  1336
133  4103  1720   47  367  2134
134  4104  1138   17  111  1266
135  4105  1689   42  242  1973
136  4106  1031   51  151  1233
137  4107   788   28  163   979
138  4108   873   10  116   999
139  4109   962   37  111  1110
140  4110  1470   54  310  1834
141  4111  1475   59  229  1763
142  4112  1876   89  390  2355
143  4113  1083   18  182  1283
144  4114   576   23  128   727

[145 rows x 5 columns]

#### add leading zeroes to PUMA to match PUMA IDs in map json file

In [24]:
puma_by_access__13['PUMA'] = puma_by_access__13['PUMA'].apply('{:0>5}'.format);
puma_by_access__13

      PUMA   1.0  2.0  3.0   All
0    00100  1111   38  439  1588
1    00200  1772   78  419  2269
2    00300  1295   64  260  1619
3    00401  1308   59  326  1693
4    00402  1175   75  258  1508
5    00403  1768   76  405  2249
6    00500  1756  107  309  2172
7    00600  1224   67  248  1539
8    00701  1069   60  359  1488
9    00702  1088   31   91  1210
10   00703  1528   53  214  1795
11   00704  1535   64  301  1900
12   00800  1231   83  326  1640
13   00901  1043   40  149  1232
14   00902   743   50  340  1133
15   00903   494   58  260   812
16   00904   911   17  119  1047
17   00905   903   14   78   995
18   00906  1310   40   93  1443
19   01000  1122   50  250  1422
20   01101   779   40  219  1038
21   01102   863   28  170  1061
22   01201   791   19  105   915
23   01202   931    9  107  1047
24   01203   822   24   94   940
25   01204  1268   43  266  1577
26   01205   815   64  350  1229
27   01206   724   85  144   953
28   01207  1422   59  187  1668
29   01300  1303   91  269  1663
..     ...   ...  ...  ...   ...
115  04003   715   57  380  1152
116  04004  1050   34  144  1228
117  04005   980   36   55  1071
118  04006   698   49  259  1006
119  04007   704   30  262   996
120  04008  1022   56  277  1355
121  04009  1951   83  241  2275
122  04010  1034   57  201  1292
123  04011   653   31  145   829
124  04012  1086   61  152  1299
125  04013  1176   50  164  1390
126  04014   896   78  691  1665
127  04015  1117   87  254  1458
128  04016  1367   45  244  1656
129  04017  1518   40  340  1898
130  04018   664   23  221   908
131  04101  1506   57  225  1788
132  04102   995   67  274  1336
133  04103  1720   47  367  2134
134  04104  1138   17  111  1266
135  04105  1689   42  242  1973
136  04106  1031   51  151  1233
137  04107   788   28  163   979
138  04108   873   10  116   999
139  04109   962   37  111  1110
140  04110  1470   54  310  1834
141  04111  1475   59  229  1763
142  04112  1876   89  390  2355
143  04113  1083   18  182  1283
144  04114   576   23  128   727

[145 rows x 5 columns]

In [25]:
adf = puma_by_access__13

In [26]:
adf = adf.rename(columns={'PUMA':'id', '1.0':'yes', '2.0':'no', '3.0':'yes but not paying'})
adf

        id   yes   no  yes but not paying   All
0    00100  1111   38                 439  1588
1    00200  1772   78                 419  2269
2    00300  1295   64                 260  1619
3    00401  1308   59                 326  1693
4    00402  1175   75                 258  1508
5    00403  1768   76                 405  2249
6    00500  1756  107                 309  2172
7    00600  1224   67                 248  1539
8    00701  1069   60                 359  1488
9    00702  1088   31                  91  1210
10   00703  1528   53                 214  1795
11   00704  1535   64                 301  1900
12   00800  1231   83                 326  1640
13   00901  1043   40                 149  1232
14   00902   743   50                 340  1133
15   00903   494   58                 260   812
16   00904   911   17                 119  1047
17   00905   903   14                  78   995
18   00906  1310   40                  93  1443
19   01000  1122   50                 250  1422
20   01101   779   40                 219  1038
21   01102   863   28                 170  1061
22   01201   791   19                 105   915
23   01202   931    9                 107  1047
24   01203   822   24                  94   940
25   01204  1268   43                 266  1577
26   01205   815   64                 350  1229
27   01206   724   85                 144   953
28   01207  1422   59                 187  1668
29   01300  1303   91                 269  1663
..     ...   ...  ...                 ...   ...
115  04003   715   57                 380  1152
116  04004  1050   34                 144  1228
117  04005   980   36                  55  1071
118  04006   698   49                 259  1006
119  04007   704   30                 262   996
120  04008  1022   56                 277  1355
121  04009  1951   83                 241  2275
122  04010  1034   57                 201  1292
123  04011   653   31                 145   829
124  04012  1086   61                 152  1299
125  04013  1176   50                 164  1390
126  04014   896   78                 691  1665
127  04015  1117   87                 254  1458
128  04016  1367   45                 244  1656
129  04017  1518   40                 340  1898
130  04018   664   23                 221   908
131  04101  1506   57                 225  1788
132  04102   995   67                 274  1336
133  04103  1720   47                 367  2134
134  04104  1138   17                 111  1266
135  04105  1689   42                 242  1973
136  04106  1031   51                 151  1233
137  04107   788   28                 163   979
138  04108   873   10                 116   999
139  04109   962   37                 111  1110
140  04110  1470   54                 310  1834
141  04111  1475   59                 229  1763
142  04112  1876   89                 390  2355
143  04113  1083   18                 182  1283
144  04114   576   23                 128   727

[145 rows x 5 columns]

### save dataframe as CSV tables for each dependent variable

In [27]:
adf.to_csv('access_puma__13.csv')

In [41]:
# if reading from CSV, check if index has turned into a column before deleting
adf.drop(adf.columns[[0]], axis=1, inplace=True)

In [51]:
# drop columns, add leading zeroes, save to CSV, and check output
drop_2_3_All = adf.drop(['no', 'yes but not paying', 'All'], axis=1)
drop_2_3_All['id'] = drop_2_3_All['id'].apply('{:0>5}'.format)
drop_2_3_All.to_csv('access_yes_only_13__id.csv', index = False)
drop_2_3_All.head()

      id   yes
0  00100  1111
1  00200  1772
2  00300  1295
3  00401  1308
4  00402  1175

In [47]:
# drop columns, add leading zeroes, save to CSV, and check output
drop_1_3_All = adf.drop(['yes', 'yes but not paying', 'All'], axis=1)
drop_1_3_All['id'] = drop_1_3_All['id'].apply('{:0>5}'.format)
drop_1_3_All.to_csv('access_no_only_13__id.csv', index = False)
drop_1_3_All.head()

      id  no
0  00100  38
1  00200  78
2  00300  64
3  00401  59
4  00402  75

In [9]:
drop_2_3_All['id'] = drop_2_3_All['id'].astype(str)

In [10]:
drop_2_3_All['yes'] = drop_2_3_All['yes'].astype(str)

   Unnamed: 0   id   yes
0           0  100  1111
1           1  200  1772
2           2  300  1295
3           3  401  1308
4           4  402  1175

   Unnamed: 0   id  no
0           0  100  38
1           1  200  78
2           2  300  64
3           3  401  59
4           4  402  75

## NYC-specific PUMAs codes > lists

In [153]:
pumas_nyc = ['3710', '3705', '3708', '3707', '3706', '3701', '3709', '3703', '3704', '3702', '4001', '3704', '3702', '4001', '4004', '4003', '4002', '4008', '4005', '4012', '4006', '4011', '4013', '4017', '4014', '4018', '4015', '4016', '4007', '4010', '4009', '3810', '3809', '3807', '3808', '3806', '3805', '3802', '3803', '3804', '3801', '4101', '4109', '4102', '4107', '4110', '4108', '4103', '4106', '4111', '4113', '4104', '4112', '4105', '4114', '3903', '3902', '3901']

In [154]:
pumas_bronx = ['3710', '3705', '3708', '3707', '3706', '3701', '3709', '3703', '3704', '3702']

In [155]:
pumas_brooklyn = ['4001', '4004', '4003', '4002', '4008', '4005', '4012', '4006', '4011', '4013', '4017', '4014', '4018', '4015', '4016', '4007', '4010', '4009']

In [156]:
pumas_manhattan = ['3810', '3809', '3807', '3808', '3806', '3805', '3802', '3803', '3804', '3801']

In [157]:
pumas_queens = ['4101', '4109', '4102', '4107', '4110', '4108', '4103', '4106', '4111', '4113', '4104', '4112', '4105', '4114']

In [159]:
pumas_staten_island = ['3903', '3902', '3901']